"""dominio completo

Revision ID: c2a8e71737f6
Revises: 0001
Create Date: 2026-07-31 13:28:12.228159+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c2a8e71737f6"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("slug", name=op.f("uq_providers_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("notify_in_app", sa.Boolean(), nullable=False),
        sa.Column("notify_telegram", sa.Boolean(), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=False),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "competitions",
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "LEAGUE",
                "CUP",
                "LEAGUE_CUP",
                "GROUP_KNOCKOUT",
                name="competition_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_competitions_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("provider_id", "external_id", name="uq_competitions_provider_external"),
        sa.UniqueConstraint("slug", name=op.f("uq_competitions_slug")),
    )
    op.create_index(
        op.f("ix_competitions_provider_id"), "competitions", ["provider_id"], unique=False
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.BigInteger(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_refresh_sessions_token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_family_id"), "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "sync_runs",
        sa.Column("provider_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_sync_runs_provider_id_providers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index(op.f("ix_sync_runs_kind"), "sync_runs", ["kind"], unique=False)
    op.create_index(op.f("ix_sync_runs_provider_id"), "sync_runs", ["provider_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=True),
        sa.Column("crest_url", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_teams_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("provider_id", "external_id", name="uq_teams_provider_external"),
    )
    op.create_index(op.f("ix_teams_provider_id"), "teams", ["provider_id"], unique=False)
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=False)
    op.create_table(
        "seasons",
        sa.Column("competition_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("competition_id", "year", name="uq_seasons_competition_year"),
    )
    op.create_index(op.f("ix_seasons_competition_id"), "seasons", ["competition_id"], unique=False)
    op.create_table(
        "pools",
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("invite_code", sa.String(length=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "RUNNING",
                "FINISHED",
                "ARCHIVED",
                name="pool_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "UNLISTED", "PUBLIC", name="pool_visibility", native_enum=False),
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=True),
        sa.Column("branding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("season_bonus_locks_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_pools_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_pools_season_id_seasons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pools")),
    )
    op.create_index(op.f("ix_pools_invite_code"), "pools", ["invite_code"], unique=True)
    op.create_index(op.f("ix_pools_owner_id"), "pools", ["owner_id"], unique=False)
    op.create_index(op.f("ix_pools_season_id"), "pools", ["season_id"], unique=False)
    op.create_index(op.f("ix_pools_slug"), "pools", ["slug"], unique=True)
    op.create_table(
        "stages",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_knockout", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_stages_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stages")),
        sa.UniqueConstraint("season_id", "name", name="uq_stages_season_name"),
    )
    op.create_index(op.f("ix_stages_season_id"), "stages", ["season_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("pool_id", sa.BigInteger(), nullable=True),
        sa.Column("entity", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["pools.id"], name=op.f("fk_audit_log_pool_id_pools"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_pool_id"), "audit_log", ["pool_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "PLAYER", name="membership_role", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "LEFT", "REMOVED", name="membership_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["pools.id"], name=op.f("fk_memberships_pool_id_pools"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("pool_id", "user_id", name="uq_memberships_pool_user"),
    )
    op.create_index(op.f("ix_memberships_pool_id"), "memberships", ["pool_id"], unique=False)
    op.create_index(
        "ix_memberships_pool_status", "memberships", ["pool_id", "status"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "rounds",
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("stage_id", sa.BigInteger(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_rounds_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["stages.id"], name=op.f("fk_rounds_stage_id_stages"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rounds")),
        sa.UniqueConstraint("season_id", "number", "name", name="uq_rounds_season_number_name"),
    )
    op.create_index(op.f("ix_rounds_season_id"), "rounds", ["season_id"], unique=False)
    op.create_index("ix_rounds_season_starts", "rounds", ["season_id", "starts_at"], unique=False)
    op.create_index(op.f("ix_rounds_stage_id"), "rounds", ["stage_id"], unique=False)
    op.create_table(
        "scoring_configs",
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("CLASSIC", "SIMPLE", "CUSTOM", name="scoring_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("knockout_advance_points", sa.Integer(), nullable=False),
        sa.Column("champion_points", sa.Integer(), nullable=False),
        sa.Column("top4_points", sa.Integer(), nullable=False),
        sa.Column("relegated_points", sa.Integer(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pools.id"],
            name=op.f("fk_scoring_configs_pool_id_pools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_configs")),
        sa.UniqueConstraint("pool_id", "version", name="uq_scoring_configs_pool_version"),
    )
    op.create_index(
        op.f("ix_scoring_configs_pool_id"), "scoring_configs", ["pool_id"], unique=False
    )
    op.create_table(
        "bonus_predictions",
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "CHAMPION",
                "TOP4",
                "RELEGATED",
                "KNOCKOUT_ADVANCE",
                name="bonus_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("locks_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_bonus_predictions_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bonus_predictions")),
        sa.UniqueConstraint(
            "membership_id", "kind", "reference_id", name="uq_bonus_membership_kind_reference"
        ),
    )
    op.create_index(
        op.f("ix_bonus_predictions_membership_id"),
        "bonus_predictions",
        ["membership_id"],
        unique=False,
    )
    op.create_table(
        "fixtures",
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("season_id", sa.BigInteger(), nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=True),
        sa.Column("home_team_id", sa.BigInteger(), nullable=False),
        sa.Column("away_team_id", sa.BigInteger(), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "LIVE",
                "HT",
                "FT",
                "AET",
                "PEN",
                "FINISHED",
                "POSTPONED",
                "SUSPENDED",
                "CANCELLED",
                "ABANDONED",
                name="fixture_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("venue", sa.String(length=160), nullable=True),
        sa.Column("home_ft", sa.Integer(), nullable=True),
        sa.Column("away_ft", sa.Integer(), nullable=True),
        sa.Column("home_et", sa.Integer(), nullable=True),
        sa.Column("away_et", sa.Integer(), nullable=True),
        sa.Column("home_pen", sa.Integer(), nullable=True),
        sa.Column("away_pen", sa.Integer(), nullable=True),
        sa.Column("winner_team_id", sa.BigInteger(), nullable=True),
        sa.Column("advancing_team_id", sa.BigInteger(), nullable=True),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settlement_dirty", sa.Boolean(), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advancing_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_advancing_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_away_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_home_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_fixtures_provider_id_providers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
            name=op.f("fk_fixtures_round_id_rounds"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_fixtures_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
        sa.UniqueConstraint("provider_id", "external_id", name="uq_fixtures_provider_external"),
    )
    op.create_index(op.f("ix_fixtures_kickoff_at"), "fixtures", ["kickoff_at"], unique=False)
    op.create_index(op.f("ix_fixtures_provider_id"), "fixtures", ["provider_id"], unique=False)
    op.create_index(op.f("ix_fixtures_round_id"), "fixtures", ["round_id"], unique=False)
    op.create_index(op.f("ix_fixtures_season_id"), "fixtures", ["season_id"], unique=False)
    op.create_index(
        "ix_fixtures_season_kickoff", "fixtures", ["season_id", "kickoff_at"], unique=False
    )
    op.create_index(
        "ix_fixtures_status_kickoff", "fixtures", ["status", "kickoff_at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column("template", sa.String(length=48), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_notifications_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint(
            "membership_id", "template", "reference_id", name="uq_notifications_dedup"
        ),
    )
    op.create_index(
        op.f("ix_notifications_membership_id"), "notifications", ["membership_id"], unique=False
    )
    op.create_index(
        "ix_notifications_status_created", "notifications", ["status", "created_at"], unique=False
    )
    op.create_table(
        "pool_rounds",
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint("multiplier >= 1", name=op.f("ck_pool_rounds_multiplier_positivo")),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["pools.id"], name=op.f("fk_pool_rounds_pool_id_pools"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
            name=op.f("fk_pool_rounds_round_id_rounds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_rounds")),
        sa.UniqueConstraint("pool_id", "round_id", name="uq_pool_rounds_pool_round"),
    )
    op.create_index(op.f("ix_pool_rounds_pool_id"), "pool_rounds", ["pool_id"], unique=False)
    op.create_index(op.f("ix_pool_rounds_round_id"), "pool_rounds", ["round_id"], unique=False)
    op.create_table(
        "standings",
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("predictions_made", sa.Integer(), nullable=False),
        sa.Column("fixtures_settled", sa.Integer(), nullable=False),
        sa.Column("criterion_hits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("previous_position", sa.Integer(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_standings_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["pools.id"], name=op.f("fk_standings_pool_id_pools"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standings")),
        sa.UniqueConstraint("pool_id", "membership_id", name="uq_standings_pool_membership"),
    )
    op.create_index(op.f("ix_standings_pool_id"), "standings", ["pool_id"], unique=False)
    op.create_index(
        "ix_standings_pool_position", "standings", ["pool_id", "position"], unique=False
    )
    op.create_table(
        "standings_snapshots",
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pools.id"],
            name=op.f("fk_standings_snapshots_pool_id_pools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
            name=op.f("fk_standings_snapshots_round_id_rounds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standings_snapshots")),
        sa.UniqueConstraint("pool_id", "round_id", name="uq_snapshots_pool_round"),
    )
    op.create_index(
        op.f("ix_standings_snapshots_pool_id"), "standings_snapshots", ["pool_id"], unique=False
    )
    op.create_table(
        "predictions",
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column("fixture_id", sa.BigInteger(), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=False),
        sa.Column("away_goals", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "home_goals <= 99 AND away_goals <= 99", name=op.f("ck_predictions_gols_plausiveis")
        ),
        sa.CheckConstraint(
            "home_goals >= 0 AND away_goals >= 0", name=op.f("ck_predictions_gols_nao_negativos")
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_predictions_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_predictions_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "membership_id", "fixture_id", name="uq_predictions_membership_fixture"
        ),
    )
    op.create_index("ix_predictions_fixture", "predictions", ["fixture_id"], unique=False)
    op.create_index(
        op.f("ix_predictions_membership_id"), "predictions", ["membership_id"], unique=False
    )
    op.create_table(
        "prediction_scores",
        sa.Column("prediction_id", sa.BigInteger(), nullable=False),
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.BigInteger(), nullable=False),
        sa.Column("fixture_id", sa.BigInteger(), nullable=False),
        sa.Column("round_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "criterion_key",
            sa.Enum(
                "EXACT",
                "WINNER_AND_ONE_SCORE",
                "WINNER_AND_GOAL_DIFF",
                "DRAW",
                "WINNER_ONLY",
                "ONE_SCORE_ONLY",
                "MISS",
                name="criterion_key",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("base_points", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column("final_points", sa.Integer(), nullable=False),
        sa.Column("scoring_version", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_prediction_scores_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_prediction_scores_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pools.id"],
            name=op.f("fk_prediction_scores_pool_id_pools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_prediction_scores_prediction_id_predictions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
            name=op.f("fk_prediction_scores_round_id_rounds"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_scores")),
        sa.UniqueConstraint("prediction_id", name="uq_prediction_scores_prediction"),
    )
    op.create_index(
        op.f("ix_prediction_scores_fixture_id"), "prediction_scores", ["fixture_id"], unique=False
    )
    op.create_index(
        "ix_prediction_scores_membership", "prediction_scores", ["membership_id"], unique=False
    )
    op.create_index(
        op.f("ix_prediction_scores_pool_id"), "prediction_scores", ["pool_id"], unique=False
    )
    op.create_index(
        op.f("ix_prediction_scores_round_id"), "prediction_scores", ["round_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prediction_scores_round_id"), table_name="prediction_scores")
    op.drop_index(op.f("ix_prediction_scores_pool_id"), table_name="prediction_scores")
    op.drop_index("ix_prediction_scores_membership", table_name="prediction_scores")
    op.drop_index(op.f("ix_prediction_scores_fixture_id"), table_name="prediction_scores")
    op.drop_table("prediction_scores")
    op.drop_index(op.f("ix_predictions_membership_id"), table_name="predictions")
    op.drop_index("ix_predictions_fixture", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_standings_snapshots_pool_id"), table_name="standings_snapshots")
    op.drop_table("standings_snapshots")
    op.drop_index("ix_standings_pool_position", table_name="standings")
    op.drop_index(op.f("ix_standings_pool_id"), table_name="standings")
    op.drop_table("standings")
    op.drop_index(op.f("ix_pool_rounds_round_id"), table_name="pool_rounds")
    op.drop_index(op.f("ix_pool_rounds_pool_id"), table_name="pool_rounds")
    op.drop_table("pool_rounds")
    op.drop_index("ix_notifications_status_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_membership_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_fixtures_status_kickoff", table_name="fixtures")
    op.drop_index("ix_fixtures_season_kickoff", table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_season_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_round_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_provider_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_kickoff_at"), table_name="fixtures")
    op.drop_table("fixtures")
    op.drop_index(op.f("ix_bonus_predictions_membership_id"), table_name="bonus_predictions")
    op.drop_table("bonus_predictions")
    op.drop_index(op.f("ix_scoring_configs_pool_id"), table_name="scoring_configs")
    op.drop_table("scoring_configs")
    op.drop_index(op.f("ix_rounds_stage_id"), table_name="rounds")
    op.drop_index("ix_rounds_season_starts", table_name="rounds")
    op.drop_index(op.f("ix_rounds_season_id"), table_name="rounds")
    op.drop_table("rounds")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index("ix_memberships_pool_status", table_name="memberships")
    op.drop_index(op.f("ix_memberships_pool_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_audit_log_pool_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_stages_season_id"), table_name="stages")
    op.drop_table("stages")
    op.drop_index(op.f("ix_pools_slug"), table_name="pools")
    op.drop_index(op.f("ix_pools_season_id"), table_name="pools")
    op.drop_index(op.f("ix_pools_owner_id"), table_name="pools")
    op.drop_index(op.f("ix_pools_invite_code"), table_name="pools")
    op.drop_table("pools")
    op.drop_index(op.f("ix_seasons_competition_id"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.drop_index(op.f("ix_teams_provider_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_sync_runs_provider_id"), table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_kind"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_family_id"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_competitions_provider_id"), table_name="competitions")
    op.drop_table("competitions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("providers")
    # ### end Alembic commands ###
