"""Modelos SQLAlchemy.

Todo modelo novo precisa ser importado aqui — o autogenerate do Alembic só
enxerga o que estiver registrado em ``Base.metadata`` no momento da geração.
"""

from app.models.base import Base, IdMixin, TimestampMixin
from app.models.catalog import (
    Competition,
    Fixture,
    Provider,
    Round,
    Season,
    Stage,
    Team,
)
from app.models.enums import (
    AuditAction,
    BonusKind,
    CompetitionType,
    CriterionKey,
    FixtureStatus,
    MembershipRole,
    MembershipStatus,
    NotificationChannelKind,
    NotificationStatus,
    NotificationTemplate,
    PoolKind,
    PoolStatus,
    PoolVisibility,
    ReportKind,
    ReportSeverity,
    ReportStatus,
    ScoringMode,
    SyncKind,
    SyncStatus,
)
from app.models.permissao import PermissionGroup, UserGroup, UserPermission
from app.models.pool import (
    Matchday,
    MatchdayFixture,
    Membership,
    Pool,
    PoolCompetition,
    PoolFixture,
    PoolRound,
    ScoringConfig,
)
from app.models.prediction import (
    BonusPrediction,
    Notification,
    Prediction,
    PredictionScore,
    Standing,
    StandingsSnapshot,
    SyncRun,
)
from app.models.report import Report, ReportAttachment, ReportComment
from app.models.user import AuditLog, RefreshSession, User

__all__ = [
    "AuditAction",
    "AuditLog",
    "Base",
    "BonusKind",
    "BonusPrediction",
    "Competition",
    "CompetitionType",
    "CriterionKey",
    "Fixture",
    "FixtureStatus",
    "IdMixin",
    "Matchday",
    "MatchdayFixture",
    "Membership",
    "MembershipRole",
    "MembershipStatus",
    "Notification",
    "NotificationChannelKind",
    "NotificationStatus",
    "NotificationTemplate",
    "PermissionGroup",
    "Pool",
    "PoolCompetition",
    "PoolFixture",
    "PoolKind",
    "PoolRound",
    "PoolStatus",
    "PoolVisibility",
    "Prediction",
    "PredictionScore",
    "Provider",
    "RefreshSession",
    "Report",
    "ReportAttachment",
    "ReportComment",
    "ReportKind",
    "ReportSeverity",
    "ReportStatus",
    "Round",
    "ScoringConfig",
    "ScoringMode",
    "Season",
    "Stage",
    "Standing",
    "StandingsSnapshot",
    "SyncKind",
    "SyncRun",
    "SyncStatus",
    "Team",
    "TimestampMixin",
    "User",
    "UserGroup",
    "UserPermission",
]
